Repository BPennie03/Discode, pull requests merged in 2024-04, with the labels that each got.

#16 Added docker compose
  Discode.sh
  bot/Dockerfile
  bot/app/Cogs/basic.py
  bot/app/bot.py
  bot/requirements.txt
  discode.sh
  docker-compose.yml
Labels: Docker

#19 Sessions cog
  bot/app/Cogs/Session.py
Labels: feature

#18 added docs to basic bot stuff
  bot/app/Cogs/basic.py
  bot/app/bot.py
Labels: documentation

#20 Start stop command
  bot/app/Cogs/Session.py
  bot/app/bot.py
Labels: enhancement, feature, Discord

#23 Getting Started
  README.md
  docs/Getting-Started.md
Labels: documentation

#24 Session timeout
  bot/app/Cogs/Session.py
Labels: feature, Discord
